### ISSUE TITLE
Comparison with locate

### ISSUE THREAD

**Issue by dufferzafar** [ngirard/lolcate-rs#10]
* Any performance benchmarks? 
    * How fast is `lolcate` in indexing the filesystem and how fast is it when querying?
    * What is the size of `lolcate` DB? (it hardly matters though!)

* Anything missing? as in something that locate can do but lolcate can't?

**Comment by ngirard** [comment]
@dufferzafar, thanks for stopping by. Hope you're doing well !

> Any performance benchmarks?

None yet. I haven't given much thought about how to perform such benchmarks properly, and TBH I'm not much interested in them. That said, I'm open to suggestions & contributions !

> Anything missing? as in something that locate can do but lolcate can't?

The following Locate options do not have an equivalent in Lolcate: `--count` `--existing` `--follow` `--transliterate` `--limit` `--nofollow` `--null`.

Also, off-topic: a quick glance at your GH profile made me discover your Cheat project. You might be interested in a similar one written in Rust, called [Navi](https://github.com/denisidoro/navi).

**Comment by dufferzafar** [comment]
> Hope you're doing well !

I am, thank you, and hope you're doing well too! :) 

Off-topic, first: I wrote `cheat` just coz I wanted to experiment with Go and because chrisallenlane's version didn't have colors by default. Now, I see that Chris has moved his project to Go and has lots of bells and whistles. There are a lot of cheatsheet tools now. I currently use [`cht.sh`](http://cht.sh/) but yeah, I have `navi` bookmarked and will check it out some time. Rust tools are in general pretty well written. A common issue with this tools though, is that they all have their own cheatsheet repo, and maybe even in different formats? So for eg. I know for a fact that I contributed to a cheatsheet for `cpdf` but I don't remember whether it was to `cht.sh` repo or to `cheat` repo. If only they could all band together and have a single repo for sheets. That'd be dope!

Now, onto locate. I currently use it and even have a `fzf` based [wrapper written around it](https://github.com/dufferzafar/dotfiles/blob/master/zsh/fzf.zsh#L64)

I read through lolcate's Readme and the only feature that I'm immediatetly interested in is the ability to specify `type` regexes, but then I thought I could write a small wrapper around locate to handle them.

I guess seeing a perf comparison would help "sell" `lolcate`, to me and to others as well, I guess.

`hyperfine` is the tool to use I think. I'll look into it and see if I can come up with some numbers. While we're at it, I'll test the `lolcate.sh` script that you linked. I'll be damned if it turns out to be faster than `locate`. 

PS: What would happen if we wrote `lolcate.sh` script with modern rust tools? `fd` to find files, `ripgrep` to search them? What format would we use to store files?

**Comment by ngirard** [comment]
@dufferzafar, I appreciate your detailed comment.

> I guess seeing a perf comparison would help "sell" lolcate, to me and to others as well, I guess.

Fair enough, I guess I should reconsider the need for benchmarks then !

> hyperfine is the tool to use I think. I'll look into it and see if I can come up with some numbers.

Now, that would be great ! Don't hesitate to use the precompiled binaries from the latest pre-release, nothing has changed since then.

> PS: What would happen if we wrote lolcate.sh script with modern rust tools?

I've actually stopped using mlocate years ago after writing a prototype in bash using lzop and ripgrep. The prototype ended up working so well, I've used it happily for very long before rewriting it in Rust. I can pastebin it to you if interested -- the shell code is not industry-grade, but hey...
The nice thing about that shell script is that the results are color-highlighted, contrary to Lolcate's current iteration. I'm sorely missing this feature, but I guess I've been too ~lazy~ busy to implement it yet ;-)

**Comment by dufferzafar** [comment]
Yeah, please send the lzop+ripgrep version to me. I'll try to do some benchmarking this weekend.

**Comment by ngirard** [comment]
> Yeah, please send the lzop+ripgrep version to me. I'll try to do some benchmarking this weekend.

Sure, there you are:

```sh
#!/usr/bin/env bash

# Requires lzop, rg                                                                                    

declare lolcate_dir=~/.local/share/lolcate-sh

declare default_db=default
declare dbname
declare search_db
declare dbpath
declare help_string

create_db(){
    local dbname=$1
    local dbpath="${lolcate_dir}/${dbname}"
    local dirs_file="${dbpath}/dirs"
    local ignore_file="${dbpath}/ignore"
    mkdir -p "$dbpath"
    touch "${dirs_file}" "${ignore_file}"
    printf "Created database '%s'.\nPlease edit:\n" "${dbname}"
    printf "  the configuration file: %s\n" "${dirs_file}"
    printf "  the ignores file:       %s\n" "${ignore_file}"
}

set_dbname(){
    dbname=$1
    dbpath="${lolcate_dir}/${dbname}"
    [[ ! -d "$dbpath" ]] && {
        echo "Wrong dbname $dbname"
        exit 1
    }
    search_db="$dbpath/db.lzop"
    ignore_file="$dbpath/ignore"
}


read -d '' help_string <<"EOF"
Lolcate - Better & faster locate for mere mortals

Creating a database
$ lolcate --create [dbname]

Updating a database
$ lolcate --update [dbname]

Searching a database
$ lolcate [--all] <pattern>   Search files matching <pattern>.
                              Using --all, all databases are searched [unimplemented].

Other options
$ lolcate --help              Print a help message and exit.
EOF

help () {
  echo -ne "$help_string\n"
}

case "$1" in
    --help)
        help && exit 0 ;;
    "")
        help && exit 1 ;;
    --create)
        shift
        create_db ${1:-$default_db}
        exit 0
        ;;
    --update)
        shift
        set_dbname ${1:-$default_db}
        dirs_file="${dbpath}/dirs"
        [[ ! -f "${dirs_file}" ]] && {
            echo "No dirs specified"
            exit 1
        }
        dirs=""
        while read d; do
            [[ $d ]] && dirs="$dirs $d";
        done < <(cat "${dirs_file}")
        rgopts="--no-ignore-parent --text --files --hidden --follow --no-ignore-vcs"
        [[ -f "${ignore_file}" ]] && rgopts="$rgopts --ignore-file=${ignore_file}"
        echo "Updating database $dbname"
        rg $rgopts $dirs 2>"${dbpath}/err.log"| lzop -1 > "${search_db}"
        exit 0
        ;;
    --db)
        shift
        set_dbname ${1:-$default_db}
        shift
        ;;
    # --all)
    #     shift
    #     ;;
    *)
        set_dbname $default_db
        ;;
esac


[[ ! -d "${lolcate_dir}" ]] && create_db ${default_db}

declare pattern=""

declare img='.*\.(jp.?g|png|gif|JP.?G)$'
declare video='.*\.(flv|mp4|mp.?g|avi|wmv|mkv|3gp|m4v|asf|webm)$'
declare doc='.*\.(pdf|chm|epub|djvu?|mobi|azw3|odf|ods|md|tex|txt|adoc)$'
declare audio='.*\.(mp3|m4a|flac|ogg)$'

case "$1" in
    --type)
        shift
        type=$1; shift
        eval "pattern='$1'\$$type"; shift
        lzop -dc ${search_db} | rg -S -N "$pattern" "$@"
        ;;
    *)
        lzop -dc ${search_db} | rg -S -N "$@"
        ;;
esac
```

**Comment by ngirard** [comment]
> I'll try to do some benchmarking this weekend.

I'm looking forward for it !
I've [added](https://github.com/ngirard/lolcate-rs/releases/tag/v0.6.0pre6) a pre-release build with link-time optimizations, please use this one.
Cheers

**Comment by ngirard** [comment]
Hey @dufferzafar, did you manage to come up with some numbers ?
I was somehow waiting for them before releasing version 0.6.0.

**Comment by dufferzafar** [comment]
Hey, no, not really. I just didn't get down to doing them. You shouldn't let me hold you back though. Please go ahead with your release!

**Comment by ngirard** [comment]
Alright, no problem!

**Comment by ngirard** [comment]
I've added the differences with Locate in the README. For further discussion about benchmarks, see #16.
