### ISSUE TITLE
Error trying to updatedb

### ISSUE THREAD

**Issue by demesm** [ngirard/lolcate-rs#11]
Tried with default config and adding a dir. Used the release binary.
Linux arch 5.6.3-arch1-1 #1 SMP PREEMPT Wed, 08 Apr 2020 07:47:16 +0000 x86_64 GNU/Linux

description = ""

# Directories to index.
dirs = [
  # "~/first/dir",
  # "/second/dir"
]

# Set to either "Dirs" or "Files" to skip directories or files
# skip = "Dirs"

# Set to true if you want skip symbolic links
ignore_symlinks = false

# Set to true if you want to ignore hidden files and directories
ignore_hidden = false

➜  ~ lolcate --update
Invalid TOML: missing field `skip` at line 1 column 1
➜  ~

**Comment by ngirard** [comment]
Hey there, hope you're doing well.
This issue has been fixed already ; please try using the [latest pre-release](https://github.com/ngirard/lolcate-rs/releases/tag/v0.6.0pre6).
Cheers
