### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ngirard** [ngirard/lolcate-rs#22]
Windows systems are currently not supported.

I'm afraid I won't actively dedicate efforts on this in the near future, but I'd happily accept contributions.

One related issue here is that Lolcate currently relies on the [dirs](https://lib.rs/crates/dirs) crate for locating configuration and data directories, and it's apparently unmaintained.

Consequently, another crate may need to be used.
There are some recent related threads on r/rust:
- [Etcetera – a new library for locating configuration, data and cache directories](https://www.reddit.com/r/rust/comments/gkvlgo/etcetera_a_new_library_for_locating_configuration) (2020-05-16)
- [directories-next & dirs-next: The new home for directories & dirs!](https://www.reddit.com/r/rust/comments/gli4pc/directoriesnext_dirsnext_the_new_home_for) (2020-05-17)

**Comment by deathtrip** [comment]
Why not just let them use WSL?
That's what it's there for.

**Comment by ngirard** [comment]
Fixed by #25. Thanks to @AlyoshaVasilieva !

**Comment by sergeevabc** [comment]
Sorry, but I have a trouble on Windows 7.
```toml
# Directories to index.
dirs = [
  "c:\",
]
```
outputs
```toml
Invalid TOML: newline in string found at line 6 column 9
```
whereas the following works fine…
``` toml
# Directories to index.
dirs = [
  "c:",
]
```
… except that output is missing a backslash after `c:` as follows
``` console
$ lolcate casab*
c:Films\Casablanca (1942)
```

**Comment by AlyoshaVasilieva** [comment]
Slashes must be escaped, for example 
```toml
dirs = [
  "C:\\",
]
```

Windows I think is slash agnostic, so using forward slashes e.g. `C:/` may also work. I just escape the slashes. Does that fix error?

**Comment by sergeevabc** [comment]
@AlyoshaVasilieva, yes, thank you. There were, however, a few errors while indexing with code 3, but that’s not critical now.
Be sure to mention in docs here that `\\` are required after a drive letter if one wants to index a whole partition on Windows.

**Comment by sergeevabc** [comment]
Aggrrhh, literal queries with wildcards, which are so common in Windows (be it `Explorer`’s search, search in a tabbed file manager like `Far`, or even a search utility like `Everything`), DO NOT work. Gosh, do local developers believe that users absorb the knowledge of regex with mother’s milk? It is OK to have it as an option, but not as a default mode, damn.
``` console
$ lolcate *.amr
Invalid regex: regex parse error:            
    *.amr                                    
    ^                                        
error: repetition operator missing expression
```
