### ISSUE TITLE
Panic on Broken Pipe

### ISSUE THREAD

**Issue by taladar** [ngirard/lolcate-rs#26]
I tried to pipe the output of lolcate into a simple head command and it panicked when head closed to input after printing the first 10 lines. This could probably be handled a bit more gracefully. Most tools seem to either ignore it completely or exit with a short "broken pipe" error message.

`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /home/taladar/.cargo/registry/src/github.com-1ecc6299db9ec823/lolcate-rs-0.9.2/src/main.rs:458:39
`

**Comment by ngirard** [comment]
Thanks for reporting.
Yeah, this should be an easy one, I saw code to handle this properly a number of times.
Would you mind providing a minimal example so that I can easily reproduce the issue ?

**Comment by taladar** [comment]
All I really did was 

`lolcate | head`

with a DB that contains more than 10 files.

**Comment by ngirard** [comment]
Fixed in latest release.
