### ISSUE TITLE
Location for data and config files

### ISSUE THREAD

**Issue by ngirard** [ngirard/lolcate-rs#5]
For now, both data and configuration files are stored in `dirs::data_local_dir()`.

As a result, database-specific configuration and data share the same subdirectory.

Would it be better to split data and configuration files ? I don't have a strong opinion about that.

**Comment by DianaNites** [comment]
Yes, better to split. Config files should be in `dirs::config_dir`

**Comment by ngirard** [comment]
Done in release 0.5.0.

This script can be used on Linux to migrate existing files to the new scheme:

```sh
    migrate_lolcate_data(){
        lolcate_data_dir=${XDG_DATA_HOME:-$HOME/.local/share}/lolcate
        lolcate_conf_dir=${XDG_CONFIG_HOME:-$HOME/.config}/lolcate
        mkdir ${lolcate_conf_dir}
        mv ${lolcate_data_dir}/config.toml ${lolcate_conf_dir}
        ls -d $lolcate_data_dir/*/ | while read db_dir; do
            db_name=$(basename $db_dir)
            db_config_dir=${lolcate_conf_dir}/${db_name}
            mkdir ${db_config_dir}
            mv ${db_dir}/{config.toml,ignores} ${db_config_dir}
        done
    }
    migrate_lolcate_data
```
